import {_electron as electron,expect} from '@playwright/test';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import JSZip from 'jszip';
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:process.env.SUPERDOCX_TEST_EXECUTABLE,args:[...(process.env.SUPERDOCX_TEST_EXECUTABLE?[]:['.']),'--user-data-dir='+await mkdtemp(tmpdir()+'/superdocx-reference-ui-')],env});
const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const file=path.resolve('artifacts/reference-ui.docx');
try{
 await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled({timeout:60000});
 await page.screenshot({path:'artifacts/ribbon-home.png'});
 await app.evaluate(({ipcMain,dialog},file)=>{
  let connected=false;
  for(const method of ['connect','status','search','disconnect'])ipcMain.removeHandler('zotero:'+method);
  ipcMain.handle('zotero:connect',()=>{connected=true;return{userID:42,username:'Test library'}});
  ipcMain.handle('zotero:status',()=>connected?{userID:42,username:'Test library'}:null);
  ipcMain.handle('zotero:disconnect',()=>{connected=false});
  ipcMain.handle('zotero:search',()=>({total:1,items:[{key:'TEST1234',data:{itemType:'journalArticle',title:'Cloud citation test',date:'2026',DOI:'10.0000/test',creators:[{creatorType:'author',firstName:'Jane',lastName:'Example'}]}}]}));
  dialog.showSaveDialog=async()=>({canceled:false,filePath:file});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});
 },file);
 await page.getByText('一份文档，无限可能。',{exact:true}).click();
 await page.getByRole('tab',{name:'引用',exact:true}).click();
 await page.getByRole('button',{name:'插入文献',exact:true}).click();
 await page.getByRole('button',{name:'Zotero 云端文献库',exact:true}).click();
 await page.screenshot({path:'artifacts/zotero-connect.png'});
 await page.getByLabel('API Key',{exact:true}).fill('A'.repeat(24));
 await page.getByRole('button',{name:'连接账户',exact:true}).click();
 await page.getByRole('button',{name:/Cloud citation test/}).click();
 await page.getByRole('button',{name:'插入引用',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'插入文献',exact:true})).toHaveCount(0);
 await expect(page.locator('#document-editor')).toContainText('[Cloud citation test]');
 await page.getByRole('button',{name:'插入或更新参考文献表'}).click();
 await page.getByRole('button',{name:'插入或更新参考文献表'}).click();
 await page.getByRole('button',{name:'保存',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('已保存到本地');
 let zip=await JSZip.loadAsync(await readFile(file)),xml=await zip.file('word/document.xml').async('string');
 assert.match(xml,/CITATION/);assert.equal((xml.match(/BIBLIOGRAPHY/g)||[]).length,1);
 await page.getByRole('button',{name:'打开文档',exact:true}).click();
 await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled({timeout:60000});
 await page.getByRole('tab',{name:'引用',exact:true}).click();
 await page.getByText('A LITTLE SPACE FOR BIG IDEAS',{exact:true}).click();
 await page.getByRole('button',{name:'插入文献',exact:true}).click();
 await page.getByRole('button',{name:/Cloud citation test/}).click();
 await page.getByRole('button',{name:'插入引用',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'插入文献',exact:true})).toHaveCount(0);
 await page.getByRole('tab',{name:'审阅',exact:true}).click();
 await page.screenshot({path:'artifacts/ribbon-review.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS cloud fixture -> native citations -> bibliography -> DOCX -> offline reuse');
}catch(e){console.log(await page.locator('body').innerText());await page.screenshot({path:'artifacts/reference-ui-failure.png'});throw e;}finally{await app.evaluate(({app})=>app.exit())}
