import {_electron as electron,expect} from '@playwright/test';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import JSZip from 'jszip';
import path from 'node:path';
import {tmpdir} from 'node:os';
import assert from 'node:assert/strict';
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:process.env.SUPERDOCX_TEST_EXECUTABLE,args:[...(process.env.SUPERDOCX_TEST_EXECUTABLE?[]:['.']),'--user-data-dir='+await mkdtemp(tmpdir()+'/superdocx-zoom-')],env});
const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled({timeout:60000});
 const output=page.locator('.status-zoom output');
 await expect(output).toHaveText('100%');
 const title=page.getByText('一份文档，无限可能。',{exact:true});
 const original=(await title.boundingBox()).width;
 await page.getByRole('button',{name:'放大文档',exact:true}).click();
 await expect(output).toHaveText('110%');
 await expect.poll(async()=>Math.round((await title.boundingBox()).width/original*100)).toBe(110);
 await expect(page.locator('.file-bar')).toHaveCSS('height','46px');
 await page.getByRole('button',{name:'重置缩放至 100%',exact:true}).click();
 const surface=page.locator('.document-scroll'),box=await surface.boundingBox();
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
 await page.keyboard.down('Control');await page.mouse.wheel(0,-60);await page.keyboard.up('Control');
 await expect.poll(async()=>parseInt(await output.textContent())).toBeGreaterThan(100);
 const zoom=await output.textContent();
 await page.mouse.wheel(0,150);
 await expect(output).toHaveText(zoom);
 await surface.dispatchEvent('wheel',{deltaY:40,ctrlKey:true,bubbles:true,cancelable:true});
 await expect.poll(()=>output.textContent()).not.toBe(zoom);
 await expect(page.locator('.unsaved-dot')).toHaveCount(0);
 assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getZoomFactor()),1);
 await surface.dispatchEvent('wheel',{deltaY:-100,metaKey:true,bubbles:true,cancelable:true});
 await expect.poll(async()=>parseInt(await output.textContent())).toBeGreaterThan(100);
 for(let i=0;i<8;i++){await surface.dispatchEvent('wheel',{deltaY:-100,ctrlKey:true,bubbles:true,cancelable:true});await page.waitForTimeout(35)}
 await expect(output).toHaveText('300%');await expect(page.getByRole('button',{name:'放大文档',exact:true})).toBeDisabled();
 for(let i=0;i<8;i++){await surface.dispatchEvent('wheel',{deltaY:100,ctrlKey:true,bubbles:true,cancelable:true});await page.waitForTimeout(35)}
 await expect(output).toHaveText('25%');await expect(page.getByRole('button',{name:'缩小文档',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'重置缩放至 100%',exact:true}).click();
 await expect(page.locator('.word-count')).not.toContainText('—');
 const before=Number((await page.locator('.word-count').innerText()).replace(/[^0-9]/g,''));
 await page.getByText('A LITTLE SPACE FOR BIG IDEAS',{exact:true}).click();
 await page.keyboard.insertText(' 中文 hello 2026 ');
 await expect.poll(async()=>Number((await page.locator('.word-count').innerText()).replace(/[^0-9]/g,''))).toBe(before+4);
 await page.getByRole('button',{name:'文档大纲',exact:true}).click();
 await expect(page.getByRole('complementary',{name:'文档大纲'})).toBeVisible();
 await page.getByRole('button',{name:'关闭大纲',exact:true}).click();
 const zip=await JSZip.loadAsync(await readFile('public/welcome.docx'));
 let xml=(await zip.file('word/document.xml').async('string')).replace('<w:document ', '<w:document xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" ');
 const spacer=Array.from({length:100},(_,i)=>'<w:p w14:paraId="'+(65536+i).toString(16).padStart(8,'0')+'"><w:r><w:t>Outline navigation test paragraph.</w:t></w:r></w:p>').join('');
 xml=xml.replace('<w:sectPr>',spacer+'<w:p w14:paraId="ABCDE123"><w:pPr><w:pStyle w:val="Heading1"/><w:outlineLvl w:val="0"/></w:pPr><w:r><w:t>Outline destination</w:t></w:r></w:p><w:sectPr>');
 zip.file('word/document.xml',xml);
 zip.file('word/styles.xml',(await zip.file('word/styles.xml').async('string')).replace('</w:styles>','<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:outlineLvl w:val="0"/></w:pPr></w:style></w:styles>'));
 const fixture=path.resolve('artifacts/outline-fixture.docx');await writeFile(fixture,await zip.generateAsync({type:'nodebuffer'}));
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});dialog.showMessageBox=async()=>({response:1});},fixture);
 await page.getByRole('button',{name:'打开文档',exact:true}).click();
 await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled({timeout:60000});
 await expect(page.locator('.filename')).toContainText('outline-fixture.docx');
 await expect(page.getByRole('alertdialog')).toHaveCount(0);
 await page.getByRole('button',{name:'文档大纲',exact:true}).click();
 await page.getByRole('button',{name:'Outline destination',exact:true}).click();
 await expect.poll(()=>surface.evaluate(e=>e.scrollTop)).toBeGreaterThan(0);
 await expect(page.locator('.outline-item[aria-current="location"]')).toHaveText('Outline destination');
 await page.screenshot({path:'artifacts/outline-panel.png'});
 await page.locator('.status-bar').screenshot({path:'artifacts/zoom-status.png'});
 assert.deepEqual(errors,[]);console.log('PASS document scaling, wheel, pinch event, normal scroll, limits, reset unchanged browser scale, live word count and heading navigation');
}catch(e){console.log(await page.locator('.outline-panel').innerText().catch(()=>''));await page.screenshot({path:'artifacts/zoom-failure.png'});throw e;}finally{await app.evaluate(({app})=>app.exit())}
